version: "3.8"
services:
  web:
    image: jarneke92/cloud_opdracht_d3:latest
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: alpinePulse
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"
volumes:
  db_data:
